// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBk2hPTAjKW-yOvt3zsnZHE0lDWV1sDSQ',
    appId: '1:852371925307:web:a06ebb4abb948eb248ef1e',
    messagingSenderId: '852371925307',
    projectId: 'attendance-app-8569d',
    authDomain: 'attendance-app-8569d.firebaseapp.com',
    storageBucket: 'attendance-app-8569d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9RRIBzAnx3d0fO7L69TzMjtum_VHsmtc',
    appId: '1:852371925307:android:d56f397c4e8f185848ef1e',
    messagingSenderId: '852371925307',
    projectId: 'attendance-app-8569d',
    storageBucket: 'attendance-app-8569d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUAcXRMQyTnCACPevGfSs8AGdB_aoMbWE',
    appId: '1:852371925307:ios:8ca0a45c2373014a48ef1e',
    messagingSenderId: '852371925307',
    projectId: 'attendance-app-8569d',
    storageBucket: 'attendance-app-8569d.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );
}
